server:
  port: 8081

spring:
  application:
    name: videoservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-videoservice:3306/videoservice
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance.id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaservice:8761/eureka

jwt:
  secret-key: 28d93268-a80b-4594-918b-5926a79a49ed
  expiration: 36000000
  prefix: Bearer
  header: Authorization

dir : /app/resources/video/

ffmpeg : /usr

