server:
  port: 8080

spring:
  application:
    name: videoservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3305/videoService
    username: hipo
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:static/db/data.sql
      mode: always
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

dir : /Users/hipo/Desktop/project/toy_project/video/videoservice/src/main/resources/video/

ffmpeg : /opt/homebrew/Cellar/ffmpeg/7.0.2

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance.id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

jwt:
  secret-key: 28d93268-a80b-4594-918b-5926a79a49ed
  expiration: 36000000
  prefix: Bearer
  header: Authorization

